POST http://localhost:5000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjJkM2FlMDhjYjVmNWFiMDkzYjBjNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0Mzk2NzE1MywiZXhwIjoxNzQzOTcwNzUzfQ.fQotFpDi5Hy6tDibd41Yux-aDEHSRjPQFgyY4zyeOC0
Content-Type: application/json

{
  "title": "New Research",
  "link": "https://example.com/article",
  "pubDate": "2023-05-15T12:00:00Z",
  "creator": "John",
  "guid": "unique-identifier-13",
  "content": "Full articlehere...",
  "post_id": "post-1",
  "post_date": "2023-05-15T00:00:00Z",
  "post_modified": "2023-05-15T01:30:00Z",
  "category": "res"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

POST http://localhost:5000/api/auth/setup

###

GET http://localhost:5000/api/articles/